### ISSUE TITLE
pg_file_settings

### ISSUE THREAD

**Issue by tobixen** [OPMDG/check_pgactivity#288] opened 2021-06-03 10:45 UTC
I think it's very useful to get an alert ...

* If the config file has been edited, but postgresql is pending a reload
* If an error has been introduced into the config file (and probably a "systemctl restart postgresql" will fail to start up postgresql again)

This information is easily available in the view pg_file_settings, which has been around since pg 9.6.

I'd suggest adding this either as a separate "service" or do a check on this view as part of the existing "settings" service.

I cannot promise anything, but if I get a green light on this one, if I find time for it, and if I understand the perl code (not my favorite language), then perhaps I will write up a pull request.  (it can't be that hard, can it?)

The task is basically just to do a check like ...

```sql
SELECT * FROM pg_file_settings WHERE not applied
```

... and yield a warning with some descriptive text if anything is returned from said query.

**Comment by Krysztophe** [comment] 2021-06-03 11:33
+1   
(Coincidence, we had a discussion about this yesterday)

You have the same problem with pg_hba.conf, and the view pg_hba_file_rules

BTW, it seems to be a duplicate of  #157

**Comment by rjuju** [comment] 2021-06-03 11:43
+ for that , and a new service would be better I think.

We should probably close this issue and switch to #157.

**Closed** 2021-06-03 12:30 UTC
Labels: duplicate, enhancement
