### ISSUE TITLE
bug in 2.6 on rhel7

### ISSUE THREAD

**Issue by joernott** [OPMDG/check_pgactivity#326] opened 2022-08-18 15:24 UTC
Hello,
we are using check_pgactivity on RHEL7.9 (using the RPMs provided by the postgres project). When we updated 2.5 (which works fine) to 2.6, we encountered the following error when creating status files:
```
can't open «/var/cache/icinga2/icinga_bgwriter.status.lock»: No such file or directory at /usr/lib64/nagios/plugins/check_pgactivity line 619.
```
The parent folder /var/cache/icinga2 is owned by the icinga2 user executing the check and has rwx rights for that user and using "sudo -u $MONITORING_USER touch /var/cache/icinga2/icinga_bgwriter.status.lock" works fine.

This is similar for all status file, this is just one example for the "icinga" database and the bgwriter check. 

I solved our current problem by downgrading back to check_pgactivity 2.5 but I'd rather use the latest released version if possible.

**Comment by rjuju** [comment] 2022-08-19 04:19
Hi,

Indeed the version 2.6 is bugged :(  The new locking approach triggers that problem when upgrading from an earlier version, as `load()` will see a storage file, but won't be able to get a shared lock on the lock file since it won't exist.

BTW, is there any reason to use a status files rather one for everything?  Creating an empty lock file should fix the problem, but clearly if you need dozen (or more) of them that's not a pleasant thing to do.

@ioguix I remember I mentioned that problem a couple of times in some versions of the patch (https://github.com/OPMDG/check_pgactivity/pull/303#discussion_r804345650 and https://github.com/OPMDG/check_pgactivity/pull/303#discussion_r814663680), but forgot to recheck this in the final versions.  You can reproduce this easily by removing the lock file, I guess this should be added to the regression tests.  We just need to double check the lock file existence in `load()` and create an empty one if needed.

**Comment by joernott** [comment] 2022-08-19 07:46
I am using a status file per check, as I didn't bother to analyze, what every check does with that file. Most of them store check specific info (how far have I read the log file, what was the last value of a counter etc.). So, in general, having different checks using the same file causes a lot of trouble.

For the moment, I am using 2.5 again, but as we manage our environments via puppet, creating lots of files on lots of servers isn't that much of an effort.

**Comment by ioguix** [comment] 2022-08-24 14:02
Hi guys,

@joernott: thanks for the report!
@rjuju: sorry, your comment has been lost in other discussions :/

What about the following fix?

~~~diff
diff --git a/check_pgactivity b/check_pgactivity
index 2aeb33a..192a53c 100755
--- a/check_pgactivity
+++ b/check_pgactivity
@@ -611,13 +611,26 @@ sub load($$$) {
     my $hostkey  = find_hostkey($host);
     my $lockfile = "${storage}.lock";
     my $all;
+    my $fh;
 
     return undef unless -e $storage;
 
     die "can not read status file «${storage}»" unless -r $storage;
 
-    open my $fh, '<', $lockfile or die "can't open «${lockfile}»: $!";
-    flock($fh, LOCK_SH) or die "can't get shared lock on «${lockfile}»: $!";
+    # During the first call of the check, the lock file might not exists yet.
+    # In this case, just create the file and use an exclusive lock on it, as we
+    # opened it in rw.
+    # If the lock file exists, open in RO and use a shared lock.
+    # See perl documentation of "flock" for details about what opening mode
+    # imply on what lock level used.
+    if ( -f $lockfile ) {
+        open $fh, '<', $lockfile or die "can't open «${lockfile}»: $!";
+        flock($fh, LOCK_SH) or die "can't get shared lock on «${lockfile}»: $!";
+    }
+    else {
+        open $fh, '>', $lockfile or die "can't open «${lockfile}»: $!";
+        flock($fh, LOCK_EX) or die "can't get exclusive lock on «${lockfile}»: $!";
+    }
 
     exit 1 unless is_storable $storage;
~~~

**Comment by rjuju** [comment] 2022-08-24 14:18
I'm worried that flock might not work as expected on some platforms, per the previous discussions.  It also seems a bit more complicated than needed though, why not just something like

```diff
diff --git a/check_pgactivity b/check_pgactivity
index b181492..a1f5061 100755
--- a/check_pgactivity
+++ b/check_pgactivity
@@ -616,6 +616,13 @@ sub load($$$) {

     die "can not read status file «${storage}»" unless -r $storage;

+    # Make sure that the lockfile exist.  It could have been removed, or just
+    # not have been created if upgrading from older versions.
+    if (not -f $lockfile) {
+        open my $fh, '>', $lockfile or die "can't open «${lockfile}»: $!";
+        close $fh or die "could not release «${lockfile}»: $!";
+    }
+
     open my $fh, '<', $lockfile or die "can't open «${lockfile}»: $!";
     flock($fh, LOCK_SH) or die "can't get shared lock on «${lockfile}»: $!";
```

**Comment by ioguix** [comment] 2022-08-24 14:31
@rjuju go for it. Can you commit it?

**Comment by rjuju** [comment] 2022-08-24 15:00
@joernott I just committed a fix for that.  Can you confirm that it also fixes the problem for you?

**Comment by rjuju** [comment] 2022-09-21 14:19
Thanks a lot for testing!

Note that we're almost ready for the 2.7 release, with the few additional recent fixes.  In the meantime I'm closing this issue, thanks again for the report.  Feel free to reopen it or create a new one if you have any other problem!

**Closed by rjuju** 2022-09-21 14:19 UTC
Labels: bug
